# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

python:
  install:
    # Install the package with the docs extra so Sphinx deps are available
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

formats: []
