# Codecov configuration file
# Documentation: https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "flipbook/_version.py"
  - "flipbook/tests/"
  - "docs/"
  - "setup.py"
  - "setup.cfg"

flags:
  unit:
    paths:
      - flipbook/
  integration:
    paths:
      - tests/